#!/bin/sh

# Sistema

printf "Limpiando paquetes huerfanos de XBPS...\n"
doas xbps-remove -o

printf "Limpiando paquetes de XBPS...\n"
doas xbps-remove -O

printf "Limpiando caché de XBPS...\n"
doas rm -rf /var/cache/xbps

# Caché
printf "Limpiando caché de nvim...\n"
find "$HOME/.cache" -mindepth 1 -maxdepth 1 ! -name 'nvim' -exec rm -rf {} \;
find "$HOME/.cache/nvim" -mindepth 1 -maxdepth 1 ! -name 'codeium' -exec rm -rf {} \;

# Temporales
# printf "Limpiando temporales...\n"
# rm -rf /tmp/*
# rm -rf "$HOME"/tmp/*

# Historiales
printf "Limpiando historiales...\n"
rm -f "$HOME"/.bash_history
rm -f "$HOME"/.python_history
rm -f "$HOME"/.node_repl_history
rm -f "$HOME"/.lesshst

# Cargo y Go
printf "Limpiando cargo...\n"
rm -rf "$HOME"/.cargo/registry/
rm -rf "$HOME"/.cargo/git/
rm -rf "$HOME"/go/pkg/
rm -rf "$HOME"/go/src/

printf  "Limpieza completa \n"
