#!/bin/sh

case "$1" in
		a)
			doas mv /etc/X11/xorg.conf.d/20-virt-monitor.conf.disabled /etc/X11/xorg.conf.d/20-virt-monitor.conf
				;;
		d)
			doas mv /etc/X11/xorg.conf.d/20-virt-monitor.conf /etc/X11/xorg.conf.d/20-virt-monitor.conf.disabled
				;;
esac
