#!/bin/sh
qemu-system-x86_64 \
  -M q35 \
  -cpu host \
  -enable-kvm \
  -vga virtio \
  -display sdl,show-cursor=on \
  -smp 4,cores=4 \
  -m 6G \
  -device AC97 \
  -boot d \
  -cdrom $1 \
  -hda $2
