#!/bin/bash

# Configurar framebuffer
xrandr --fb 2944x1080

# Configurar resoluciones de las pantallas
xrandr --output HDMI-0 --mode 1920x1080 --pos 0x0 --primary
xrandr --output DP-1 --mode 1024x576 --pos 1920x0

