#!/bin/sh
qemu-system-x86_64 \
  -M q35 \
	-drive if=pflash,format=raw,readonly=on,file="/usr/share/qemu/edk2-x86_64-code.fd" \
	-drive if=pflash,format=raw,file="/usr/share/qemu/edk2-i386-vars.fd" \
  -cpu host \
  -enable-kvm \
  -vga virtio \
  -display sdl,show-cursor=on \
  -smp 2,cores=2 \
  -m 2G \
  -device AC97 \
  -usb \
  -hda $1
