#!/bin/sh

qemu-system-x86_64 \
	-M q35 \
	-drive if=pflash,format=raw,readonly=on,file="/usr/share/qemu/edk2-x86_64-code.fd" \
	-drive if=pflash,format=raw,readonly=on,file="/usr/share/qemu/edk2-i386-vars.fd" \
	-cpu host \
	-enable-kvm \
	-vga qxl \
	-display sdl,show-cursor=on \
	-smp 2,cores=2 \
	-m 2G \
	-boot d \
	-cdrom $1 \
	-hda $2
