#!/bin/bash

# Comprobar si el comando 'sensors' está instalado
if ! command -v sensors &> /dev/null; then
    echo "El comando 'sensors' no está instalado. Por favor, instala lm_sensors con 'sudo xbps-install lm_sensors' u otro gestor de paquetes."
    exit 1
fi

# Obtener la temperatura actual
temperature=$(sensors | grep "temp1" | awk '{print $2}')

# Mostrar la temperatura
echo "La temperatura de tu PC es: $temperature"
